const roomAdjs2 = [
  "Pony",
  "Music",
  "Terror",
  "Hope",
  "Love",
  "Deviant",
  "Robot",
  "Mammal",
  "Bagel",
  "Pizza",
  "Culinary",
  "Art",
  "Housekeeping",
  "Crossdressing",
  "Intelligence",
  "Philosophy",
  "Anime",
  "Manga",
  "Cosplay",
  "Maid",
  "Catgirl",
  "Flounder",
  "Dropout",
  "Weed",
  "Lucid Dreaming",
  "Astral Projection",
  "Surveillance",
  "Development",
  "Construction",
  "Exploration",
  "Space Travel",
  "Chemistry",
  "Anxiety Disorder",
  "Hypocrisy",
  "Criminal",
  "Fashion",
  "Interior Design",
  "Technology",
  "Princess",
  "Proletariat",
  "Empathy",
  "Indigestion",
  "Bisexual",
  "Human Sexuality",
  "Nerd",
  "Astrophysics",
  "Engineering",
  "Rare Earth Metal",
  "Mining",
  "Data Analysis",
  "Ice Cream",
  "Doughnut",
  "Cake",
  "Glassworking",
  "Blacksmithing",
  "Jewelry-Making",
  "Degenerate",
  "Waifu",
  "Husbando",
  "Yaoi",
  "Yuri",
  "Bara",
  "Shipping",
  "Fan-Fiction",
  "Comic",
  "Doctor",
  "Time Travel",
  "Psychology",
  "Sushi",
  "Wizard",
  "Librarian",
  "Magician",
  "Astronaut",
  "Whittling",
  "Burrito",
  "Fish Taco",
  "Piracy",
  "Avian",
  "Research",
  "Film",
  "Animation",
  "Documentation",
  "Garbage",
  "Melon Farmer",
  "Gardening",
  "Unicorn",
  "Mecha",
  "Therapy",
  "Assassin",
  "Waffle",
  "Fried Chicken",
  "Broken Dream",
  "Relationship",
  "Drug",
  "Botanical",
  "Horticultural",
  "Domination",
  "Architecture",
  "Tulpamancing",
  "Titty",
];

export default roomAdjs2;
