---
- name: ensure meteor is at the latest version
  shell: curl https://install.meteor.com | /bin/sh
  args:
    creates: /usr/local/bin/meteor

- name: ensure build tools are at the latest version
  apt: pkg=build-essential state=latest

- name: copy nodejs 0.10 archive
  copy: src=../../node-v0.10.41.tar.gz dest=/var/tmp/node-v0.10.41.tar.gz
  register: node
  when: bootstrap
- name: unpack nodejs 0.10 archive
  unarchive: src=/var/tmp/node-v0.10.41.tar.gz dest=/var/tmp/ copy=false
  when: bootstrap
- name: configure, build, and install nodejs 0.10
  command: "/usr/bin/make install -j{{ makej }} chdir=/var/tmp/node-v0.10.41"
  when: bootstrap
