---
- name: ensure meteor is at the latest version
  shell: curl https://install.meteor.com | /bin/sh
  args:
    creates: /usr/local/bin/meteor
- name: ensure nodejs is at the latest version
  apt: pkg=nodejs state=latest
