---
- name: ensure imagemagick is at the latest version
  apt: pkg=imagemagick state=latest
- name: ensure ffmpeg is at the latest version
  apt: pkg=ffmpeg state=latest

- name: Add group "comfycafe"
  group: name=comfycafe
- name: Add user "comfycafe"
  user: name=comfycafe group=comfycafe home=/srv/ComfyCafe/
- name: load email config
  include_vars: ~/.mailgun.json

- name: copy ComfyCafe systemd unit file
  template: src=ComfyCafe.service.j2 dest=/etc/systemd/system/ComfyCafe.service
  register: service_file
  notify:
  - start ComfyCafe
- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  when: service_file.changed
- name: install nodejs packages
  command: /usr/local/bin/npm install
  args:
    chdir: /srv/ComfyCafe/bundle/programs/server
  notify:
  - restart ComfyCafe
