---
- name: ensure mongodb-org is at the latest version
  apt: pkg=mongodb-org state=latest
  notify:
  - restart mongod
- name: copy mongod configuration
  template: src=mongod.conf.j2 dest=/etc/mongod.conf
  notify:
  - reload mongod
