---
- name: ensure imagemagick is at the latest version
  apt: pkg=imagemagick state=latest
- name: ensure ffmpeg is at the latest version
  apt: pkg=ffmpeg state=latest

- name: Add group "teruimages"
  group: name=teruimages
- name: Add user "teruimages"
  user: name=teruimages group=teruimages home=/srv/TeruImages/
- name: load email config
  include_vars: ~/.mailgun.json
- name: copy TeruImages systemd unit file
  template: src=TeruImages.service.j2 dest=/etc/systemd/system/TeruImages.service
  register: service_file
  notify:
  - start TeruImages
- name: systemctl daemon-reload
  shell: systemctl daemon-reload
  when: service_file.changed

- name: ensure git is at the latest version
  apt: pkg=git state=latest
  when: useGit
- name: pull from TeruImages repo
  git: repo={{ repository }} dest=/srv/TeruImages/src version=develop
  register: pulled
  when: useGit
- name: build Meteor bundle
  command: /usr/local/bin/meteor build --directory /srv/TeruImages
  args:
    chdir: /srv/TeruImages/src
  register: bundle
  when: useGit and pulled.changed

- name: copy Meteor bundle
  copy: src=../TeruImages.tar.gz dest=/srv/TeruImages/TeruImages.tar.gz
  register: bundle
  when: not useGit and local
- name: unpack Meteor bundle
  unarchive: src=/srv/TeruImages/TeruImages.tar.gz dest=/srv/TeruImages copy=false
  when: not useGit and bundle.changed

- name: install nodejs packages
  command: /usr/local/bin/npm install
  args:
    chdir: /srv/TeruImages/bundle/programs/server
  notify:
  - restart TeruImages
