---
- name: ensure nginx is at the latest version
  apt: pkg=nginx state=latest
  notify:
  - restart nginx
- name: copy nginx websocket configuration
  template: src=websocket_pool.conf.j2 dest=/etc/nginx/conf.d/websocket_pool.conf
  notify:
  - reload nginx
- name: copy nginx connection upgrade configuration
  template: src=connection_upgrade.conf.j2 dest=/etc/nginx/conf.d/connection_upgrade.conf
  notify:
  - reload nginx
- name: copy nginx site configuration
  template: src=site.conf.j2 dest=/etc/nginx/sites-enabled/teru-images.conf
  notify:
  - reload nginx
- name: copy nginx cors-anywhere configuration
  template: src=cors-anywhere.conf.j2 dest=/etc/nginx/sites-enabled/cors-anywhere.conf
  notify:
  - reload nginx
- name: remove nginx default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
  - reload nginx
  when: default_server
