var adjs1 = [
  "Downtown",
  "Upstate",
  "Imperial",
  "Federal",
  "Underground",
  "Illegal",
  "Civil",
  "Rainbow",
  "Dreamy",
  "Depraved",
  "Erudite",
  "Progressive",
  "Traditional",
  "Mysterious",
  "Unknown",
  "New Age",
  "Modern",
  "Contemporary",
  "Ancient",
  "Classical",
  "National",
  "International",
  "Colorful",
  "Covert",
  "Controversial",
  "Subversive",
  "Transgressive",
  "Unsupervised",
  "Subsidized",
  "Abstract",
  "Conceptual",
  "Fancy",
  "Experimental",
  "Indie",
  "Hipster",
  "Cutting Edge",
  "Bleeding Edge",
  "Unstable",
  "Confederate",
  "Invasive",
  "Undocumented",
  "Persuasive",
  "Dangerous",
  "Smooth",
  "Hippie",
  "Central",
  "Manly",
  "Feminine",
  "Dynamic",
  "Democratic",
  "Sovereign",
  "Quantum",
  "Communist",
  "Communal",
  "Family-Friendly",
  "Misleading",
  "Destructive",
  "Chocolate",
  "Vanilla",
  "Caramel",
  "South African",
  "Australian",
  "European",
  "American",
  "Italian",
  "Japanese",
  "German",
  "United",
  "Lunar",
  "Funky",
  "Junior",
  "Master",
  "Advanced",
  "Optimistic",
  "Special",
  "Cultural",
  "Social",
  "My Little",
  "Pink",
  "Short-Term",
  "Fresh",
  "Stylish",
  "New York",
  "San Francisco",
  "Over-Saturated",
  "Aggressive",
  "Pervasive",
  "Bavarian",
  "California",
  "Alaskan",
  "Mexican",
  "Official",
  "Roman",
  "Unofficial",
  "Dark Blue",
  "French",
  "Global",
  "Worldwide",
  "Intergalactic",
  "Stellar",
  "Sensual",
  "Pop Punk",
  "Pepperoni",
  "Legendary",
  "Professional",
  "Obscure",
  "Esoteric",
  "Archaic",
  "Mystical",
  "Enigmatic",
  "Ethical",
  "Sustainable",
  "Grassroots",
  "Northern",
  "Southern",
  "Western",
  "Eastern",
  "Platinum",
  "Fraudulent",
];

var adjs2 = [
  "Pony",
  "Music",
  "Terror",
  "Hope",
  "Love",
  "Deviant",
  "Robot",
  "Mammal",
  "Bagel",
  "Pizza",
  "Culinary",
  "Art",
  "Housekeeping",
  "Crossdressing",
  "Intelligence",
  "Philosophy",
  "Anime",
  "Manga",
  "Cosplay",
  "Maid",
  "Catgirl",
  "Floundering",
  "Lucid Dreaming",
  "Astral Projection",
  "Surveillance",
  "Development",
  "Construction",
  "Exploration",
  "Space Travel",
  "Chemistry",
  "Anxiety Disorder",
  "Hypocrisy",
  "Criminal",
  "Fashion",
  "Interior Design",
  "Technology",
  "Princess",
  "Proletariat",
  "Empathy",
  "Indigestion",
  "Bisexual",
  "Human Sexuality",
  "Nerd",
  "Astrophysics",
  "Engineering",
  "Rare Earth Metal",
  "Mining",
  "Data Analysis",
  "Ice Cream",
  "Doughnut",
  "Cake",
  "Glassworking",
  "Blacksmithing",
  "Jewelry-Making",
  "Degenerate",
  "Waifu",
  "Husbando",
  "Yaoi",
  "Yuri",
  "Bara",
  "Shipping",
  "Fan-Fiction",
  "Comic",
  "Doctor",
  "Time Travel",
  "Psychology",
  "Sushi",
  "Wizard",
  "Librarian",
  "Magician",
  "Astronaut",
  "Whittling",
  "Burrito",
  "Fish Taco",
  "Piracy",
  "Avian",
  "Research",
  "Film",
  "Animation",
  "Documentation",
  "Garbage",
  "Melon Farmer",
  "Gardening",
  "Unicorn",
  "Mecha",
  "Therapy",
  "Assassin",
  "Waffle",
  "Fried Chicken",
  "Botanical",
  "Horticultural",
  "Domination",
  "Architecture",
];

var things = [
  "Club",
  "Team",
  "Clubhouse",
  "Treehouse",
  "Inc.",
  "LLC",
  "Company",
  "Coalition",
  "Forum",
  "Board",
  "Council",
  "Tribunal",
  "Organization",
  "Atelier",
  "University",
  "Academy",
  "Brotherhood",
  "Cult",
  "Group",
  "Association",
  "Tribe",
  "Community",
  "Congress",
  "Gang",
  "Cartel",
  "Trust",
  "Force",
  "Collective",
  "Ensemble",
  "Orchestra",
  "Guild",
  "Agency",
  "Insurgency",
  "Army",
  "Militia",
  "Navy",
  "Bureau",
  "Republic",
  "Colony",
  "Society",
  "Initiative",
  "Theater",
  "Utopia",
  "League",
  "Task Force",
  "Department",
  "Mafia",
  "Reserves",
  "Convention",
  "Conference",
  "Summit",
  "Institute",
  "Division",
  "Party",
  "Operation",
  "Uprising",
  "Revolution",
  "Rebellion",
  "Reformation",
  "Movement",
  "Fraternity",
  "Sorority",
  "Alliance",
  "Fund",
  "Resources",
  "Collectors",
  "Advisors",
  "Counselors",
  "Heist",
  "Plan",
];

generateRoom = function () {
  var adj1 = _.sample(adjs1);
  var adj2 = _.sample(adjs2);
  var thing = _.sample(things);

  return [adj1, adj2, thing].join(" ");
};
